import NavBar from "../components/navbar";

function Transactions() {
  return (
    <>
      <NavBar />
      <h1>Transactions</h1>
      <p>
        On that screen you should have selected the network and account you are
        using. This screen enable you to enter a set of calls and will{" "}
      </p>
      <h2>Enter a multicall</h2>
      <p>
        For now, copy/paste a list of call as they would be generated by the
        dapp. So far, I assume it would be made of contract addresses, selector
        hash and parameter values
      </p>
      <h2>**Later** Reverse Engineer the transaction</h2>
      <p>
        This could be an added value to help the user understand what the
        transaction is doing. A good source of inspiration for the associated
        feature could be this document by Ledger, i.e.{" "}
        <a href="https://developers.ledger.com/docs/clear-signing/getting-started">
          Enhancing Security through Clear Signing
        </a>
        . Among the feature that we could provide, we could:
      </p>
      <ul>
        <li>
          Check if the contract sources are available and if the binaries
          matches the sources
        </li>
        <li>Check if the contract has been audited</li>
        <li>
          Provide a description, i.e. text associated with what the contract
          does
        </li>
        <li>Revert the selector to provide the methods that are being used</li>
        <li>
          Provide a description of the function being called, i.e. a text
          associated with that selector
        </li>
        <li>Revert the parameter values to show what the values are</li>
        <li>
          Provide a description for each one of the parameters, i.e. a text
          associated with every selector
        </li>
        <li>
          Integrate ChatGPT or another LLM and say what the function is supposed
          to do. For details of what we can do with the application
        </li>
        <li>Assess the risk of running the transaction</li>
      </ul>
      <h2>Generate the payload</h2>
      <p>
        The signer should generate the payload based on the multicall that has
        been provided and the account that is being used.
      </p>
      <h2>Estimate the fees</h2>
      <p>
        The signer should be able to provide an estimate of the cost as well as
        the maximum fee that will be used
      </p>
      <h2>Sign and submit the transaction</h2>
      <p>
        Assuming the user wants to submit the transaction to the network, signer
        should sign the transaction and submit it to the network
      </p>
      <h2>Monitor the execution</h2>
      <p>
        Transactions that have been submitted should be monitored for executions
      </p>
      <h2>Report (Receipt) the transaction</h2>
      <p>
        Once the transaction has succeeded or failed, it should remain in the
        history of transactions
      </p>
    </>
  );
}

export default Transactions;
