name: docs

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        branch: develop